import { Quartier, Post } from "./types";

export const quartiers: Quartier[] = [
  // ── Montréal ──────────────────────────────────────────────────────────────
  { slug: "plateau-mont-royal",     nom: "Plateau-Mont-Royal",         ville: "Montréal", couleur: "bg-rose-500" },
  { slug: "rosemont",               nom: "Rosemont–La Petite-Patrie",  ville: "Montréal", couleur: "bg-orange-500" },
  { slug: "verdun",                 nom: "Verdun",                     ville: "Montréal", couleur: "bg-teal-500" },
  { slug: "hochelaga",              nom: "Hochelaga-Maisonneuve",      ville: "Montréal", couleur: "bg-purple-500" },
  { slug: "griffintown",            nom: "Griffintown",                ville: "Montréal", couleur: "bg-blue-500" },
  { slug: "mile-end",               nom: "Mile End",                   ville: "Montréal", couleur: "bg-pink-500" },
  { slug: "outremont",              nom: "Outremont",                  ville: "Montréal", couleur: "bg-emerald-500" },
  { slug: "villeray",               nom: "Villeray",                   ville: "Montréal", couleur: "bg-amber-500" },
  { slug: "saint-henri",            nom: "Saint-Henri",                ville: "Montréal", couleur: "bg-cyan-600" },
  { slug: "cote-des-neiges",        nom: "Côte-des-Neiges",            ville: "Montréal", couleur: "bg-lime-600" },
  { slug: "notre-dame-de-grace",    nom: "Notre-Dame-de-Grâce",        ville: "Montréal", couleur: "bg-violet-500" },
  { slug: "petite-bourgogne",       nom: "Petite-Bourgogne",           ville: "Montréal", couleur: "bg-red-400" },
  { slug: "vieux-montreal",         nom: "Vieux-Montréal",             ville: "Montréal", couleur: "bg-stone-500" },
  { slug: "pointe-saint-charles",   nom: "Pointe-Saint-Charles",       ville: "Montréal", couleur: "bg-sky-500" },
  { slug: "lachine",                nom: "Lachine",                    ville: "Montréal", couleur: "bg-fuchsia-500" },
  { slug: "lasalle",                nom: "LaSalle",                    ville: "Montréal", couleur: "bg-yellow-600" },
  { slug: "anjou",                  nom: "Anjou",                      ville: "Montréal", couleur: "bg-green-600" },
  { slug: "saint-leonard",          nom: "Saint-Léonard",              ville: "Montréal", couleur: "bg-blue-600" },
  { slug: "montreal-nord",          nom: "Montréal-Nord",              ville: "Montréal", couleur: "bg-orange-600" },
  { slug: "riviere-des-prairies",   nom: "Rivière-des-Prairies",       ville: "Montréal", couleur: "bg-teal-600" },
  { slug: "saint-laurent",          nom: "Saint-Laurent",              ville: "Montréal", couleur: "bg-rose-600" },
  { slug: "dollard-des-ormeaux",    nom: "Dollard-des-Ormeaux",        ville: "Montréal", couleur: "bg-purple-600" },
  { slug: "mont-royal",             nom: "Mont-Royal",                 ville: "Montréal", couleur: "bg-indigo-400" },
  { slug: "westmount",              nom: "Westmount",                  ville: "Montréal", couleur: "bg-slate-500" },
  // ── Québec ────────────────────────────────────────────────────────────────
  { slug: "saint-sauveur",          nom: "Saint-Sauveur",              ville: "Québec",   couleur: "bg-green-500" },
  { slug: "limoilou",               nom: "Limoilou",                   ville: "Québec",   couleur: "bg-yellow-500" },
  { slug: "vieux-port-qc",          nom: "Vieux-Port",                 ville: "Québec",   couleur: "bg-red-500" },
  { slug: "saint-roch",             nom: "Saint-Roch",                 ville: "Québec",   couleur: "bg-indigo-500" },
];

export const posts: Post[] = [
  {
    id: "1",
    titre: "Nouveau propriétaire sur le Plateau — quelques questions sur la copropriété",
    contenu: "Bonjour! On vient d'acheter notre premier plex au coin de Laurier et Saint-Denis. Est-ce que quelqu'un peut m'expliquer comment fonctionne la déclaration de copropriété? Notre notaire nous a remis un document de 80 pages et je me sens un peu perdu.",
    auteur: "marie.belanger",
    quartier: quartiers[0],
    categorie: "question",
    creeLe: "2026-03-20T08:32:00Z",
    nbCommentaires: 14,
    nbVotes: 47,
    nbVues: 312,
    epingle: false,
  },
  {
    id: "2",
    titre: "ALERTE — dégât d'eau au 3450 Masson, locataires informez votre proprio",
    contenu: "Ce matin vers 6h, une conduite a cédé dans la cage d'escalier de l'immeuble au 3450 rue Masson. Si vous demeurez aux alentours, vérifiez vos sous-sols. La Ville a été contactée mais les délais sont longs.",
    auteur: "simon.tremblay",
    quartier: quartiers[1],
    categorie: "alerte",
    creeLe: "2026-03-20T07:15:00Z",
    nbCommentaires: 31,
    nbVotes: 128,
    nbVues: 1847,
    epingle: true,
  },
  {
    id: "3",
    titre: "Rénovation de salle de bain — recommandez-vous des entrepreneurs fiables à Verdun?",
    contenu: "On cherche un plombier-rénovateur sérieux pour refaire la salle de bain de notre condo. Budget autour de 12 000$. On a eu des mauvaises expériences par le passé avec des entrepreneurs qui disparaissent en cours de projet.",
    auteur: "luc.gagnon",
    quartier: quartiers[2],
    categorie: "renovation",
    creeLe: "2026-03-19T21:45:00Z",
    nbCommentaires: 22,
    nbVotes: 63,
    nbVues: 541,
  },
  {
    id: "4",
    titre: "À louer — 4½ lumineux, chauffé-éclairé inclus, Hochelaga",
    contenu: "Beau 4½ au 2e étage d'un duplex bien entretenu. Planchers de bois franc, cuisine rénovée, grande cour arrière partagée. Disponible le 1er juillet. 1 350$/mois, chauffé-éclairé inclus. Aucun animal, non-fumeur svp.",
    auteur: "proprioHoch",
    quartier: quartiers[3],
    categorie: "location",
    creeLe: "2026-03-19T18:00:00Z",
    nbCommentaires: 8,
    nbVotes: 35,
    nbVues: 289,
  },
  {
    id: "5",
    titre: "Mise en vente — condo neuf Griffintown, 2 chambres, garage",
    contenu: "Superbe condo de 2 chambres dans un immeuble de 2022. Vue sur le canal Lachine, terrasse privée, stationnement intérieur. Prix demandé: 549 000$. Visite libre samedi prochain entre 13h et 16h.",
    auteur: "agentImmo_mtl",
    quartier: quartiers[4],
    categorie: "vente",
    creeLe: "2026-03-19T14:30:00Z",
    nbCommentaires: 5,
    nbVotes: 19,
    nbVues: 178,
  },
  {
    id: "6",
    titre: "Bruit excessif du voisin du dessus — quels sont mes recours?",
    contenu: "Ça fait trois semaines que mon voisin marche avec des talons durs jusqu'à 2h du matin. J'ai frappé à sa porte deux fois. Je veux savoir si je peux faire quelque chose de plus formel sans aller directement à la Régie du logement.",
    auteur: "residents.limoilou",
    quartier: quartiers[25],
    categorie: "voisinage",
    creeLe: "2026-03-18T23:10:00Z",
    nbCommentaires: 41,
    nbVotes: 89,
    nbVues: 763,
  },
  {
    id: "7",
    titre: "Revitalisation de Saint-Roch — vos impressions après 5 ans?",
    contenu: "J'ai quitté Saint-Roch en 2021 et je reviens m'y installer. Le quartier a beaucoup changé. Quelqu'un peut me donner un portrait honnête de la situation actuelle? Prix, mixité sociale, commerces, sécurité?",
    auteur: "retour_en_ville",
    quartier: quartiers[27],
    categorie: "question",
    creeLe: "2026-03-18T16:00:00Z",
    nbCommentaires: 67,
    nbVotes: 154,
    nbVues: 2103,
  },
  {
    id: "8",
    titre: "Droit de préemption — la Ville a refusé d'acheter notre immeuble, que faire?",
    contenu: "On a soumis notre immeuble à 6 logements au droit de préemption de la Ville de Montréal comme requis. La Ville n'a pas exercé son droit. On peut donc vendre librement? Quelqu'un a vécu la même situation récemment?",
    auteur: "proprio.rosemont",
    quartier: quartiers[1],
    categorie: "question",
    creeLe: "2026-03-17T11:20:00Z",
    nbCommentaires: 18,
    nbVotes: 72,
    nbVues: 634,
  },
];
