import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const postsData = [
  {
    titre: "Nouveau propriétaire sur le Plateau — quelques questions sur la copropriété",
    contenu: "Bonjour! On vient d'acheter notre premier plex au coin de Laurier et Saint-Denis. Est-ce que quelqu'un peut m'expliquer comment fonctionne la déclaration de copropriété? Notre notaire nous a remis un document de 80 pages et je me sens un peu perdu.",
    auteurNom: "marie.belanger",
    quartierSlug: "plateau-mont-royal",
    villeSlug: "montreal",
    categorie: "question",
    creeLe: new Date("2026-03-20T08:32:00Z"),
    nbCommentaires: 14,
    nbVotes: 47,
    nbVues: 312,
    epingle: false,
  },
  {
    titre: "ALERTE — dégât d'eau au 3450 Masson, locataires informez votre proprio",
    contenu: "Ce matin vers 6h, une conduite a cédé dans la cage d'escalier de l'immeuble au 3450 rue Masson. Si vous demeurez aux alentours, vérifiez vos sous-sols. La Ville a été contactée mais les délais sont longs.",
    auteurNom: "simon.tremblay",
    quartierSlug: "rosemont",
    villeSlug: "montreal",
    categorie: "alerte",
    creeLe: new Date("2026-03-20T07:15:00Z"),
    nbCommentaires: 31,
    nbVotes: 128,
    nbVues: 1847,
    epingle: true,
  },
  {
    titre: "Rénovation de salle de bain — recommandez-vous des entrepreneurs fiables à Verdun?",
    contenu: "On cherche un plombier-rénovateur sérieux pour refaire la salle de bain de notre condo. Budget autour de 12 000$. On a eu des mauvaises expériences par le passé avec des entrepreneurs qui disparaissent en cours de projet.",
    auteurNom: "luc.gagnon",
    quartierSlug: "verdun",
    villeSlug: "montreal",
    categorie: "renovation",
    creeLe: new Date("2026-03-19T21:45:00Z"),
    nbCommentaires: 22,
    nbVotes: 63,
    nbVues: 541,
    epingle: false,
  },
  {
    titre: "À louer — 4½ lumineux, chauffé-éclairé inclus, Hochelaga",
    contenu: "Beau 4½ au 2e étage d'un duplex bien entretenu. Planchers de bois franc, cuisine rénovée, grande cour arrière partagée. Disponible le 1er juillet. 1 350$/mois, chauffé-éclairé inclus. Aucun animal, non-fumeur svp.",
    auteurNom: "proprioHoch",
    quartierSlug: "hochelaga",
    villeSlug: "montreal",
    categorie: "location",
    creeLe: new Date("2026-03-19T18:00:00Z"),
    nbCommentaires: 8,
    nbVotes: 35,
    nbVues: 289,
    epingle: false,
  },
  {
    titre: "Mise en vente — condo neuf Griffintown, 2 chambres, garage",
    contenu: "Superbe condo de 2 chambres dans un immeuble de 2022. Vue sur le canal Lachine, terrasse privée, stationnement intérieur. Prix demandé: 549 000$. Visite libre samedi prochain entre 13h et 16h.",
    auteurNom: "agentImmo_mtl",
    quartierSlug: "griffintown",
    villeSlug: "montreal",
    categorie: "vente",
    creeLe: new Date("2026-03-19T14:30:00Z"),
    nbCommentaires: 5,
    nbVotes: 19,
    nbVues: 178,
    epingle: false,
  },
  {
    titre: "Bruit excessif du voisin du dessus — quels sont mes recours?",
    contenu: "Ça fait trois semaines que mon voisin marche avec des talons durs jusqu'à 2h du matin. J'ai frappé à sa porte deux fois. Je veux savoir si je peux faire quelque chose de plus formel sans aller directement à la Régie du logement.",
    auteurNom: "residents.limoilou",
    quartierSlug: "limoilou",
    villeSlug: "quebec",
    categorie: "voisinage",
    creeLe: new Date("2026-03-18T23:10:00Z"),
    nbCommentaires: 41,
    nbVotes: 89,
    nbVues: 763,
    epingle: false,
  },
  {
    titre: "Revitalisation de Saint-Roch — vos impressions après 5 ans?",
    contenu: "J'ai quitté Saint-Roch en 2021 et je reviens m'y installer. Le quartier a beaucoup changé. Quelqu'un peut me donner un portrait honnête de la situation actuelle? Prix, mixité sociale, commerces, sécurité?",
    auteurNom: "retour_en_ville",
    quartierSlug: "saint-roch",
    villeSlug: "quebec",
    categorie: "question",
    creeLe: new Date("2026-03-18T16:00:00Z"),
    nbCommentaires: 67,
    nbVotes: 154,
    nbVues: 2103,
    epingle: false,
  },
  {
    titre: "Droit de préemption — la Ville a refusé d'acheter notre immeuble, que faire?",
    contenu: "On a soumis notre immeuble à 6 logements au droit de préemption de la Ville de Montréal comme requis. La Ville n'a pas exercé son droit. On peut donc vendre librement? Quelqu'un a vécu la même situation récemment?",
    auteurNom: "proprio.rosemont",
    quartierSlug: "rosemont",
    villeSlug: "montreal",
    categorie: "question",
    creeLe: new Date("2026-03-17T11:20:00Z"),
    nbCommentaires: 18,
    nbVotes: 72,
    nbVues: 634,
    epingle: false,
  },
  {
    titre: "Achat dans Chomedey — est-ce que les taxes scolaires sont incluses dans l'offre?",
    contenu: "On fait une offre sur un semi-détaché à Chomedey. L'agent nous dit que les taxes scolaires sont séparées. C'est normal? Comment ça se calcule pour l'année en cours si on achète en mai?",
    auteurNom: "premierachat.laval",
    quartierSlug: "chomedey",
    villeSlug: "laval",
    categorie: "question",
    creeLe: new Date("2026-03-19T10:00:00Z"),
    nbCommentaires: 9,
    nbVotes: 28,
    nbVues: 201,
    epingle: false,
  },
  {
    titre: "Hull — transformation du secteur du marché, vos avis?",
    contenu: "Le nouveau projet de condos près du marché By/Hull va changer complètement le secteur. Est-ce que les résidents ont été consultés? J'ai l'impression que le quartier perd son identité au profit des fonctionnaires fédéraux.",
    auteurNom: "hull.citoyen",
    quartierSlug: "hull",
    villeSlug: "gatineau",
    categorie: "voisinage",
    creeLe: new Date("2026-03-18T09:30:00Z"),
    nbCommentaires: 33,
    nbVotes: 76,
    nbVues: 445,
    epingle: false,
  },
  {
    titre: "Sherbrooke — plex à vendre secteur Fleurimont, bonne affaire?",
    contenu: "Je regarde un duplex sur le boul. Bourque à Fleurimont, demandé 395 000$. Le revenu brut annuel est d'environ 24 000$. Est-ce que c'est dans les normes pour Sherbrooke en 2026? Le marché s'est beaucoup resserré.",
    auteurNom: "investisseur.estrois",
    quartierSlug: "fleurimont",
    villeSlug: "sherbrooke",
    categorie: "vente",
    creeLe: new Date("2026-03-17T14:00:00Z"),
    nbCommentaires: 15,
    nbVotes: 41,
    nbVues: 318,
    epingle: false,
  },
  {
    titre: "Trois-Rivières — hausse des loyers dans le centre-ville, témoignages?",
    contenu: "Mon propriétaire me demande une augmentation de 12% pour le renouvellement de bail. On est au centre-ville de Trois-Rivières. J'ai l'impression que la ville suit la tendance de Montréal avec quelques années de retard. Quelqu'un d'autre vit ça?",
    auteurNom: "locataire.3r",
    quartierSlug: "trois-rivieres",
    villeSlug: "trois-rivieres",
    categorie: "question",
    creeLe: new Date("2026-03-16T18:45:00Z"),
    nbCommentaires: 24,
    nbVotes: 93,
    nbVues: 712,
    epingle: false,
  },
];

async function main() {
  console.log("Seeding posts...");
  await prisma.post.deleteMany();
  for (const data of postsData) {
    await prisma.post.create({ data });
  }
  console.log(`✓ ${postsData.length} posts insérés.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
